frr version 8.1
frr defaults traditional
hostname ixp_man
no ipv6 forwarding
!
router bgp 65501
 no bgp ebgp-requires-policy
 ! Peer with Edge Routers
 neighbor 185.2.2.5 remote-as 65000
 neighbor 185.2.2.6 remote-as 65000
 ! Peer with Internet Client
 neighbor 185.2.2.100 remote-as 65200
 !
 address-family ipv4 unicast
  neighbor 185.2.2.5 route-server-client
  neighbor 185.2.2.6 route-server-client
  neighbor 185.2.2.100 route-server-client
 exit-address-family
!
