---
- name: Traffic Engineering - Degrade BT ISP Route
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Inject DEGRADE policy and apply to Edge Router 1
      ansible.builtin.shell: |
        docker exec -i clab-ixp-te-lab-edge_router_1 sr_cli <<EOF
        enter candidate
        # Create the policy to lower Local Pref and Prepend AS Path
        set / routing-policy policy DEGRADE-ISP default-action policy-result accept
        set / routing-policy policy DEGRADE-ISP default-action bgp local-preference set 50
        set / routing-policy policy DEGRADE-ISP default-action bgp as-path prepend as-number 65000 repeat-n 3
        
        # Apply the policy to the BT ISP group
        set / network-instance default protocols bgp group EBGP-BT export-policy [ DEGRADE-ISP ] import-policy [ DEGRADE-ISP ]
        commit save
        EOF
      register: cli_output

    - name: Display Router Output
      ansible.builtin.debug:
        msg: "{{ cli_output.stdout_lines }}"
