frr version 8.1
frr defaults traditional
hostname internet_client
no ipv6 forwarding
!
router bgp 65200
 no bgp ebgp-requires-policy
 ! Peer with ISP BT
 neighbor 8.8.8.1 remote-as 2856
 ! Peer with ISP VMO2
 neighbor 9.9.9.1 remote-as 5089
 ! Peer with IXP-LON Route Server
 neighbor 185.1.1.254 remote-as 65500
 ! Peer with IXP-MAN Route Server
 neighbor 185.2.2.254 remote-as 65501
!
