frr version 8.1
frr defaults traditional
hostname ixp_lon
no ipv6 forwarding
!
router bgp 65500
 no bgp ebgp-requires-policy
 neighbor 185.1.1.5 remote-as 65000
 neighbor 185.1.1.6 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 185.1.1.5 route-server-client
  neighbor 185.1.1.6 route-server-client
 exit-address-family
!
