frr version 8.1
frr defaults traditional
hostname ixp_lon
no ipv6 forwarding
!
ip route 8.8.8.0/24 185.1.1.100
ip route 9.9.9.0/24 185.1.1.100
!
router bgp 65500
 no bgp ebgp-requires-policy
 neighbor 185.1.1.5 remote-as 65000
 neighbor 185.1.1.6 remote-as 65000
 !
 address-family ipv4 unicast
  network 8.8.8.0/24
  network 9.9.9.0/24
  neighbor 185.1.1.5 route-server-client
  neighbor 185.1.1.6 route-server-client
 exit-address-family
!
